<?php

declare(strict_types=1);
/**
 * Generate blocks.css file with imports for all block styles.
 *
 * This script scans the resources/blocks directory and automatically
 * generates CSS imports for all blocks that have a {block-name}.css file.
 *
 * Run this script manually or add it to your build process.
 */

$blocks_dir = __DIR__ . '/../../resources/blocks';
$output_file = __DIR__ . '/../../resources/css/blocks.css';

if ( ! is_dir($blocks_dir)) {
    echo "Blocks directory not found: {$blocks_dir}\n";
    exit(1);
}

$imports = [];
$blocks = glob($blocks_dir . '/*', GLOB_ONLYDIR);

foreach ($blocks as $block_dir) {
    $block_name = basename($block_dir);
    // Look for {block-name}.css file.
    $style_file = $block_dir . '/' . $block_name . '.css';

    if (file_exists($style_file)) {
        $imports[] = "@import '../blocks/{$block_name}/{$block_name}.css';";
    }
}

$content = "/* Auto-generated block styles - do not edit manually */\n";
$content .= "/* This file is automatically generated by app/Scripts/generate-blocks-css.php */\n";
$content .= "/* Run: php app/Scripts/generate-blocks-css.php */\n\n";

if ( ! empty($imports)) {
    $content .= implode("\n", $imports) . "\n";
} else {
    $content .= "/* No blocks with {block-name}.css found */\n";
}

file_put_contents($output_file, $content);
echo 'Generated blocks.css with ' . count($imports) . " block imports.\n";
